name: Renegade
favicon: null
layout_spectrum: 0.4831743105314672
typography_spectrum: 0.020525678992271423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4375
  lightness: 0.14779218612238765
  saturation: 0.6875
  rhythmicContrast: 0.3907667244784534
purpose: []
